version: '3'

services:
  tests:
    image: "lehrermarktplatz/php-dev-test:latest"
    command: [ "-s", "basic" ]
    environment:
      APP_HOST: "172.17.0.1"
      APP_PORT: "8000"


  network_mode: host
  # your "vouchers" application config here
